### ISSUE TITLE
Posts Title and Body Validation

### ISSUE THREAD

**Issue by noushinquazi** [rice-apps/BeakSpeak#39]
goal: disallow the user from posting a title that exceeds a limit n and a body that exceeds a limit m. 

design choices to consider: when a limit is hit, perhaps the form can instantly give feedback OR give feedback when submission is attempted. the form SHOULD NOT eliminate the user's current post, as that would add friction.

Also, consider what this would look like for comments. Since comments do not use a form, perhaps processing the comment and giving feedback when a user attempts to comment is the best option.

where to look at code: modify the fields inside the form options object located inside Components/New.js

**Comment by parkermg** [comment]
Added title limiter at 100 chars, body at 1000. In future, could extend body limit and simply show preview of it from the main screen if the body is greater than a certain length. Problematically, a post's text is rendered through the same logic regardless of whether from the main or post detail screen, so it is hard to programmatically distinguish whether a post's body should be previewed.

**Comment by noushinquazi** [comment]
one solution for tracking if in main or post detail: add a field to the post-model that will hold the value "main" or "detail". add a setter function to post-model that takes as input a string and sets the field to this value. in main, before passing a post object to PostData, call this setter and pass "main". likewise for post detail.
